### PR TITLE
updating packages/vulns/base image to respond to github vulnerability report

### PR DESCRIPTION
**Pull request by benaduggan**
There was a django vulnerability with the version we were on, so I updated it, and a bunch of other packages too

### CODE REVIEW

**Comment by benaduggan** [comment]
Also, it's [Hacktoberfest](https://hacktoberfest.digitalocean.com)!

**Comment by benaduggan** [comment]
:+1: I still need 2 more PRs! :worried: Got anything else small I could take a look at?

**Comment by amunn33** [comment]
If you'd like to take a look at the main navbar's station tab, it'd be nice
to group those by country! Without diving too far into it I wasn't sure how
to do that with the ng-multi-select

**Comment by benaduggan** [comment]
cool! I'll try to take a look at that!

**Pull request merged**
